CAPESandbox/community

modules/signatures/ransomware_fileextensions.py
modules/signatures/ransomware_files.py

ransomware_files.py: Escape square brackets. It will miss detection and is causing FPs in https://capesandbox.com/analysis/6218/, which is DNS tunneling DLL.
ransomware_fileextensions.py: Update to include variations of Prolock extentions.

Update ransomware signatures

---

modules/signatures/recon_fingerprint.py

noticed a syntax error getting logged when running this sig.  Looks like a left over colon from the past change.

correct syntax error in recon_fingerprint.py

---

modules/signatures/office_exploit.py

Error in displaying created process due to it appearing in ApplicationName

Change Commandline to ApplicationName in Equation Exploit

---

modules/signatures/network_dga_fraunhofer.py

This signature detects the likely usage of Domain Generation algorithms by
matching all dns requests of a sandbox run against a pre-built bloomfilter.
The bloomfilter contains the active DGA domains from today, tomorrow and
yesterday and is based on the intelligence of the Fraunhofer DGArchive.
The check against the bloomfilter is really quick. Only if we have hits
we'll proceed and match the DGA domain to its DGA/malware family by
performing a dict lookup that is preloaded in memory.
The bloomfilter and the lookup dict are created by the create_bloom.py
script of the CAPEv2 repository and placed within the /data folder of
the community repository. The update process can be performed
manually via running the script on the local machine before
signature push/pull or via cronjob task. …

add network_dga_fraunhofer signature

---

data/yara/CAPE/EnigmaStub.yar

EnigmaStub is generic detection and does not associate as a specific/dedicated malware family. Examples:
https://capesandbox.com/analysis/151824/ (RedLine)
https://capesandbox.com/analysis/152239/ (NjRAT)
https://capesandbox.com/analysis/153215/ (Alfonoso)
https://capesandbox.com/analysis/144103/ (NjRAT)
https://capesandbox.com/analysis/144052/ (NjRAT)
https://capesandbox.com/analysis/138504/ (AsyncRAT)

Remove type due to family misidentification

---

modules/signatures/pdf_annot_urls.py

Came across this when I through a PDF of the FreeBSD handbook at it for testing.
This outright skips mailto: as those can't contain attachments.
http:// and http:// are only skipped if it does not contain a additional "/". So "http://foo.com" is skipped, but "http://foo.com/malware.com" will trigger it.

fix mailto:, https://, and http:// handling for the pdf_annot_urls

---

modules/signatures/windows_utilities.py

This is to help avoid matching on something like "\"C:\\Program Files (x86)\\Adobe\\Reader 11.0\\Reader\\AcroRd32.exe\" --channel=1824.1.41778424 --type=renderer  \"C:\\Users\\Fifi\\AppData\\Local\\Temp\\freebsd handbook.pdf\"", which it currently does. Currently that sig will trigger as type is present in the string instead of being used as a command. To avoid this, make sure it is not a switch via checking if it starts with a -.
Was originally thinking of a second check for = at the end of it as well, but a few of these have spaces at the end, meaning it is not doable.

clean up uses_windows_utilities to avoid improper matching

---

modules/signatures/move_file_on_reboot.py

If Windows decides to do any sort of icon cache maintenance during a run, it results in noise.
I've run into this randomly happening on Win10.

update the signature move_file_on_reboot to ignore icon cache noise

---

modules/signatures/ransomware_filemodifications.py

Not sure what exactly triggers it, but Win10 will every so often decide to flush the icon cache and when this happens this is improperly triggered.
To avoid this if this condition is matched, the count is not incremented.
```
if origfile.find("\\AppData\\Local\\Microsoft\\Windows\\Explorer\\iconcache_") and \
newfile.find("\\AppData\\Local\\Microsoft\\Windows\\Explorer\\IconCacheToDelete\\"):
```

ransomware_file_modifications fix for file_modifications to avoid triggering on win10 flushing the icon cache

---

modules/signatures/network_questionable_http_path.py

This is for hitting on HTTP/HTTPS fetches out to hosts that have likely been compromised.
common_dirs contains a lists of directorys that are commonly given 777 perms and get drek written to them. Or with out 777 written to  via the a compromised PHP script or the like. If it gets a hit it looks through common_types for common file types used to hold malware. Then if gets a hit there, it returns a hit for the rule.
Was hoping to get a slightly questionable rule with low confidence as it is not looking for file types, just directory names, but could not get that to play nicely and not hit redundantly when the main rule hits.

add network_questionable_http_path.py which checks for commonly exploitable paths being used to pull questionable files down

---

modules/signatures/cape_browser_mitb.py

Add signature to identify when injection is done into a browser process which may indicate man-in-browser intent (web injects/banking trojan etc.)
Test with explorer (removed in live sig) as didn't have sample that did browser injection to hand but idea of sig working and identifying matching process from CAPE data here

Create signature to detect browser injection (MITB)

---

modules/signatures/wiper.py

Add signature for when potential wiper overwrites multiple files with \x00. This can be seen in CaddyWiper which was detected being used in Ukraine 14/3/2022. 
There are other ways to overwrite files and random bytes would be another but I do not have a detection method for that technique yet although I am thinking along the lines of overwriting multiple files it did not create but this would be a lower severity signature due to it being also indicative of installers.
CaddyWiper

Create signature for \x00 wiper malware

---

modules/signatures/alphacrypt_apis.py
modules/signatures/cape_browser_mitb.py

For consistency's sake...
Of 676 signatures, 283 have the parameter `ttp` and two have the parameter `ttps`. Nomenclature-wise I think the attribute should be `ttps`, but fixing two signatures is a lot easier than fixing 283.

ttps should be ttp

---

modules/signatures/rat_karagany.py

This is the only use for the `filter_apinames` field in logic 
https://github.com/kevoreilly/CAPEv2/blob/5b3ceea578e0d90cbd61886b443a37cb13160c64/lib/cuckoo/core/plugins.py#L500
And to get to that point, the signature must be `evented`.

To use filter_apinames, signature must be evented

---

modules/signatures/infostealer_apocalypse.py
modules/signatures/rat_lodarat.py
modules/signatures/trojan_ursnif.py

For consistency https://github.com/kevoreilly/CAPEv2/blob/6de60f504e87fd8a59a182a3f3cdad8b604adddd/lib/cuckoo/common/abstracts.py#L723
Only `families` is used https://github.com/kevoreilly/CAPEv2/blob/5b3ceea578e0d90cbd61886b443a37cb13160c64/lib/cuckoo/core/plugins.py#L604

Family should be families

---

modules/signatures/dead_link.py
modules/signatures/execution_suspicious.py

"binary", "file" and "command" are more common mark names than these one-offs.

Changing mark names for consistency

---

modules/signatures/remcos.py

From what I can find, this issue is only present for the remcos_files signature

Removing unnecessary list for mark value

---

modules/signatures/bootkit.py
modules/signatures/persistence_autorun.py
modules/signatures/powershell_command.py
modules/signatures/reads_self.py

I notice that some of the mbcs are put in the ttps array.
And also one typo "0B0006" -> "OB0006"

fix misplace mbc tags & typo

---

modules/signatures/network_cnc_http.py

Signature was not running because it relied on `on_complete` to be called, but that is for evented signatures only.
Indicator regex did not match any valid URI since it required a URI to start with an IP

Using run for nonevented sig, updating indicator regex

---

modules/signatures/antidebug_setunhandledexceptionfilter.py
modules/signatures/antivm_network_adapter.py
modules/signatures/crypto_apis.py
modules/signatures/dll_load_uncommon.py
modules/signatures/dynamic_function_loading.py
modules/signatures/exploit_heapspray.py
modules/signatures/malware_data_encryption.py
modules/signatures/office_dll_loading.py
modules/signatures/stack_pivot.py
modules/signatures/stealth_timelimit.py

Based on a sample set of > 100k safe Office documents, these are the signatures that cause the most FPs.

Tweaking scores and adding safelists of processes

---

modules/signatures/deletes_shadowcopies.py

Found vssadmin was being called in a sample I was handed. Went to write a sig for it and found deletes_shadow_copies, but it was not triggering. When looking at it, I found that it was missing checking NtCreateUserProcess, which in this case was what was being used to call it.

 check NtCreateUserProcess API as well for the deletes_shadow_copies sig

---

modules/signatures/bcdedit_command.py
modules/signatures/bypass_uac.py
modules/signatures/compile_dotnet_code.py
modules/signatures/deletes_system_backup.py
modules/signatures/disables_drives_autodisconnect.py
modules/signatures/exploitation_framework_koadic.py
modules/signatures/injection_needextension.py
modules/signatures/ransomware_sodinokibi.py
modules/signatures/rat_trochilus.py
modules/signatures/script_downloader.py
modules/signatures/stack_pivot.py
modules/signatures/stealth_childproc.py
modules/signatures/whitelisting_bypass_dev_utils.py
modules/signatures/wmi.py

So  #324 got me thinking where else this may be relevant. So I went through looking for at other places CreateProcessInternalW or ShellExecuteExW were used and added NtCreateUserProcess where it should be relevant.
Pretty much any where that CreateProcessInternalW is used with the arg CommandLine, checking NtCreateUserProcess as well is likely a good idea.

add NtCreateUserProcess checking in a few more places

---

modules/signatures/procmem_yara.py

Out of millions of benign files, this signature was never raised. For malicious files, it is frequently raised. That is a spectacular true-positive rate.

Adjusting the severities of procmem_yara since it has a very high TP rate

---

modules/signatures/network_payload_download.py

- `recv` has argument "buffer"
- `InternetReadFile` has argument "Buffer"

Fix network_payload_downaload signature with wrong argument name

---

modules/signatures/office_exploit.py

This signature is seen being falsely raised whenever IE launches an HTML file for a benign webpage such as google.com. This looks like a regression from https://github.com/cccs-kevin/community-1/commit/1ba482d034327919ae83a653d294c3aab7b1c1b4#diff-8ddc70403e284237d5742c1864a6ddd4979857d74b8e0d270d8c484e6186eb4d.
Therefore we should check if the only data is that of marked calls and if so it is a FP.

Avoiding FPs for office CVE exploit

---

modules/reporting/runstatistics.py

Fixes errors for runs in which zero files were dropped.
```
2023-01-25 16:11:52,768 [Task 95110] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "RunStatistics": object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 715, in process
current.run(self.results)
File "/opt/CAPEv2/utils/../modules/reporting/runstatistics.py", line 93, in run
detail["dropped_files"] = self.getDroppedFileCount(results)
File "/opt/CAPEv2/utils/../modules/reporting/runstatistics.py", line 19, in getDroppedFileCount
return len(results.get("dropped"))
TypeError: object of type 'NoneType' has no len()
```

add a fix for if a report has zero dropped files

---

modules/signatures/ransomware_filemodifications.py

First improvement/clean-up pass of this sig:
- Updated description to indicate potential for it being ransomware or a wiper
- Limit call marking to only first 10 calls. This is so it does not go crazy and mark a lot of calls.
- Updated behaviour to append to main description. This is due to them appearing after call markings which were not clear.
- Added in overwriting files that existed before using CreateFile. There are other APIs and things that can do this but need to research more.
Note: Some behaviours no longer work due to limits on dropped files, also this sig does not cover all ransomware modifications, possible methods to achieve these such as APIs or wipers (when they are messing with files and not just trashing MBR and things). A lot do trash files though. To cover these …

Make various updates to ransomware file modifications sig

---

modules/signatures/accesses_public_folder.py

This signature was inspired by a talk given at 35th Annual FIRST Conference in Montreal, Canada by https://twitter.com/malmoeb of InfoGuard AG.

Adding a signature for when a sample accesses the C:\Users\Public directory

---

modules/signatures/stealth_network.py

Closes https://cccs.atlassian.net/browse/AL-2548
This signature reflects a gap in the CAPE monitor, rather than something that is actually "stealth". That is why I propose we decrease the severity from 3 to 1. I am seeing this signature raised on a ton of benign HTML files simply because the monitor does not log the network API call. This signature is still useful though (and could be useful for finding samples to use when improving the monitor) so we should definitely keep it.
Also it would be nice to have the hosts / domains included in the signature data for context so I added that.

Adding data to stealth_network signature, reducing score

---

modules/signatures/ransomware_filemodifications.py

This PR is to address the large amount of false-positives seen in benign files with this signature.
- Use a list of handles to maintain handles used
- Ignore files found in the Internet Explorer cache directory
- If a file is rewritten more than once, ignore
- Log files involved in the signature data

Adjusting ransomware_file_modifications signature for FPs on benign files

---

modules/signatures/infostealer_cookies.py

This PR is the result of a high number of false positives for benign files, specifically with the path `C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCookies`

Updating the infostealer_cookies to address FPs for certain files

---

analyzer/windows/modules/auxiliary/procmon.py

I found a problem with procmon settings not working when enabled.  
I fixed the following two things
- Misnaming of the directory where procmon related files are stored
- Uploading to directories not allowed by whitelist

Fixed problem with Procmon module not working

---

modules/signatures/windows/script_misc.py

Add signature for JavaScript timer usage when executing from a script process (possible evasion used in various scripts like GootLoader.

Add signature for JavaScript timer

---

modules/signatures/windows/malware_data_encryption.py

When only one of `[compname, username]` is set, the `Crypt*` buffers are checked against an empty string making the condition always pass.

Fix bug in encrypt_pcinfo signature

---

modules/signatures/windows/virus.py

This plugin introduces a while condition that can end up becoming an infinite loop. 
Seen in SHA256: 
- 0b577cbf1914b04d92c9a07fe5bca8e07451573ad3ea11299948edcd1ec86413
- 0757a85f8e19e972ea6e140d8b5f69f58b533471c0b5a603005fa0ca9667d48a

fix signatures/wndows/virus.py infinite loop

---

modules/signatures/loader_alien.py

This PR/commit is an open source contribution from the Proofpoint Threat Detection & Research team as part of the Virus Bulletin 2024 conference paper and presentation (https://www.virusbulletin.com/conference/vb2024/abstracts/life-and-death-building-detection-forensics-and-intelligence-scale/).
It's nothing much, but believe me, it was not easy to get this through the approval process.
AlienLoader
AlienLoader is a Java dropper used by TA577, which was seen dropping Pikabot. Proofpoint researchers dubbed AlienLoader due to the popular threat label name from VirusTotal. Looking at the decompiled binary and its behavior in a sandbox run identifies numerous detection opportunities. The sample reaches out to the payload URL and tries to create and write the downloaded payload to a file under …

add loader_alien.py

---

modules/signatures/windows/infostealer_browser.py

The signature is only triggered by the `NtReadFile` API, which requires the file to exist; however, if the browser is not installed on the guest VM, the signature won't be triggered. Most info stealers first check for the file's existence using the `PathFileExists` API, which internally calls the `NtQueryAttributesFile` API.
Also, I have added a counter to make the signature fired up if it hits a defined threshold, not in general to avoid false-positives.

Change the logic of detection

---

modules/signatures/windows/antivm_recent_files.py

According to [Malcore](https://www.linkedin.com/posts/malcore_today-we-will-be-continuing-our-vm-detection-activity-7257056918160986115-Ihh9?utm_source=share&utm_medium=member_desktop), checking the last access time of recent files offers a clever approach to identifying virtualization environments. If recent files haven't been accessed within a certain threshold, like 5 days, it could indicate the system is running on a virtual machine.

Detecting Virtualization via RecentFiles

---

modules/signatures/windows/abuse_hvci.py
modules/signatures/windows/lolbas.py
modules/signatures/windows/misc.py

I've added about 11 new artifacts related to registry modifications and LOLBAS binary executions from [Elastic Repo](https://github.com/elastic/protections-artifacts/tree/main/behavior/rules/windows)

Adding new artifacts

---

modules/signatures/all/pdf_annot_urls.py

This path check references an undefined variable, causing CAPE processing to fail for every analysis.
The regression was introduced in c78f264a2fdb52d614c8da3aba4889718f5b905c.

Remove the path check in PDF_Annot_URLs_Checker.__init__

---

modules/signatures/all/intel_threatfox.py

This is an experimental signature for ThreatFox. It still needs the following assistance/work but if the api is entered from your threatfox account (free to create) this will work on DNS requests. 
So what is needed:
- I need to add in lookups for other network types (IP connections and other types if necessary)
The main thing is ideally is rather than the API being entered in the signature it is entered in processing.conf. I have created the following in my processing.conf under community:
[threatfox]
enabled = no
apikey = ""
My question is how do I call that checking that it is enabled and then more specifically how do I then pull the apikey from this into the signature.
So I think something like:
processing_conf = Config("processing")
if processing_conf.threatfox.enabled:
apikey = …

Create ThreatFox Intel Sig

---

modules/signatures/windows/memory_scraping.py

This signature is to detect memory scraping type behaviours. This could be for credential theft, information theft or injection.
For example here it is for injection in shadowpad/poisonplug (79c2c656eac34f628406855c9fafe36161ac423c071d9b20b64f4f511c9ec241)

Create signature for reading memory of remote process

---

modules/signatures/all/static_pe_anomaly.py

Add signature to highlight overlay. For example (shadowpad):
That contains a rar overlay that has additional payloads embedded in it

Add signature for PE overlay

---

modules/signatures/windows/injection_thread.py

`self.get_argument` returns a string so whether the target process and source process are equal or not, it always be true, so we need to convert it to integer

Fix injection_thread.py

---

modules/parsers/utils.py

Will help in Assemblyline deployments where the containers that have zero network access so waiting until timeout does have a negative impact on scalability of the file analysis

Control request timeout via env
