- modules/signatures/territorial_disputes_sigs.py
https://www.crysys.hu/publications/files/tedi/ukatemicrysys_territorialdispute.pdf
> Add territorial disputes signatures sig

- modules/signatures/ransomware_crypto.py
This is an experimental signature I had from before. I did some quick tests and seems to work as intended.
> Add experimental ransomware signature on crypt calls

- modules/signatures/whitelisting_bypass_dev_utils.py
Nearly all .NET-based keyloggers do this.
> Add signature for app whitelisting bypass via dev utilities

- modules/signatures/collects_systeminfo_cmd.py
https://capesandbox.com/analysis/2141/ is one example.
> Add signature for system/user/network info collection via command line

- data/yara/CAPE/Echelon.yar
> Add Echelon infostealer Yara signature

- modules/signatures/office_suspicious_process.py
> Update message on signature to "child processes"

- modules/signatures/deletes_shadowcopies.py
https://www.capesandbox.com/analysis/7692/#
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/vssadmin-resize-shadowstorage
"Resizing the storage association may cause shadow copies to disappear."
> Add detection for shadowstorage resize

- modules/signatures/persistence_ifeo.py
https://attack.mitre.org/techniques/T1183/
> Add detection for persistence/injection via IFEO

- modules/signatures/office_exploit.py
> Update office_exploit for detecting EQNEDT32 network connectivity

- modules/signatures/office_dll_loading.py
https://blog.pwntario.com/team-posts/antons-posts/hunting-malicious-macros
> Add hunting artifacts for suspicious Office DLL loading

- modules/signatures/credential_dumping.py
> Add signature for credential dumping using registry

- modules/signatures/ransomware_fileextensions.py
RYUK successor deployed following enterprise lateral movement.
> Add conti ransomware extension

- modules/signatures/execution_suspicious.py
Creating processes from an anomalous location; in this case executing files from user Temp/roaming directories but more can be added.
> Add signature for creating a process from a suspicious location

- modules/signatures/credential_access.py
Adds detection for enabling WDigest to store credentials in plaintext
> Add credential access via WDigest

- data/yara/CAPE/Ekans.yar
- modules/signatures/accesses_mailslot.py
- modules/signatures/accesses_sysvol.py
- modules/signatures/credential_dumping.py
- modules/signatures/exploitation_framework_koadic.py
- modules/signatures/ransomware_snake_mutex.py
- modules/signatures/remote_desktop.py
> Some more updates

- modules/signatures/network_explorer.py
https://capesandbox.com/analysis/46440/
> Add detection for explorer.exe establishing network connections

- data/yara/CAPE/AgentTeslaV3.yar
- modules/signatures/http_request.py
https://capesandbox.com/analysis/58538/
> Signature updates

- data/yara/CAPE/PyInstaller.yar
- data/yara/CAPE/RDPWrap.yar
- modules/signatures/persistence_remotedesktop.py
- modules/signatures/rat_modi.py
- modules/signatures/recyclebin_access.py
* Update cape_types
* Slight module updates
> Minor changes

- modules/signatures/bootkit.py
> Add sig for IOCTL_SCSI_PASS_THROUGH (possible bootkit)

- data/yara/CAPE/RemoteUtilitiesRAT.yar
https://capesandbox.com/analysis/67384/
> Add RemoteUtilities RAT Yara signature

- modules/signatures/malware_data_encryption.py
> Add signature for encrypting PC info (possibly for C2)

- data/yara/CAPE/Apocalypse.yar
- data/yara/CAPE/IRCBot.yar
- data/yara/CAPE/Osno.yar
- data/yara/binaries/indicator_tools.yar
Osno
https://capesandbox.com/analysis/68033/
IRCBot
https://capesandbox.com/analysis/67772/
https://capesandbox.com/analysis/67773/
Apocalypse
https://capesandbox.com/analysis/67936/
https://capesandbox.com/analysis/67935/
> Add and update Yara signatures

- modules/signatures/account_modifications.py
- modules/signatures/infostealer_apocalypse.py
- modules/signatures/network_dns_suspicious.py
- modules/signatures/rat_lodarat.py
- modules/signatures/trojan_ursnif.py
https://capesandbox.com/analysis/67881/ > ursnif_api.py did not trigger.
https://capesandbox.com/analysis/67867/ > account_modifications.py
> Add and update behavior signatures

- modules/signatures/process_discovery.py
> Add signatures for process discovery

- modules/signatures/clamav.py
Signed-off-by: Matteo Manzoni <manzoni.matteo@mailfence.com>
> Sanitize suricata extracted files key access

- data/yara/CAPE/Poullight.yar
- modules/signatures/infostealer_echelon.py
- modules/signatures/infostealer_poullight.py
Poullight:
https://capesandbox.com/analysis/106142/
https://capesandbox.com/analysis/106715/
https://capesandbox.com/analysis/106716/
> Add new signatures

- data/yara/binaries/ole_vba.yar
https://www.fireeye.com/blog/threat-research/2020/11/purgalicious-vba-macro-obfuscation-with-vba-purging.html
> Add fireeye yara sigs for VBA purging

- data/yara/CAPE/Amadey.yar
- data/yara/CAPE/QuasarStealer.yar
- data/yara/CAPE/RansomEXX.yar
- data/yara/CAPE/RedLine.yar
- data/yara/binaries/indicator_suspicious.yar
QuasarStealer:
https://capesandbox.com/analysis/108045/
https://capesandbox.com/analysis/108044/
Amady  (I had this updated but forgot to PR):
https://capesandbox.com/analysis/107939/
RansomEXX:
https://capesandbox.com/analysis/108057/
> Add and updaet Yara signatures

- data/yara/CAPE/Dharma.yara
- data/yara/CAPE/Downloaders.yar
- data/yara/CAPE/FujinamaRAT.yar
- data/yara/CAPE/HDLocker.yar
- data/yara/CAPE/Phorpiex.yar
- data/yara/CAPE/PoshKeylogger.yar
- data/yara/CAPE/QnapCrypt.yar
- data/yara/CAPE/RevengeRAT.yar
- data/yara/CAPE/Sn0wLogger.yar
- data/yara/CAPE/SunCrypt.yar
- data/yara/CAPE/Vovalex.yar
- data/yara/binaries/indicator_suspicious.yar
- data/yara/binaries/indicator_tools.yar
- modules/signatures/infostealer_screenshot.py
infostealer_screenshot.py > https://capesandbox.com/analysis/115490/ > Behavior > Page 6
> Add and update Yara and behavior signatures

- data/yara/CAPE/BuerLoader.yar
> Add BuerLoader.yar

- data/yara/CAPE/Meteorite.yar
https://capesandbox.com/analysis/125682/
> Add Meteorite downloader sig

- modules/signatures/cryptopools.py
Just fixing a small typo in the signature description :)
Also, the severty field was set to 10 and i didnt see any other signature with this kind of severity, so i guess it's 1..? 
Tagging @doomedraven @bartblaze because it says you're the authors :)
> fix a small typo

- modules/signatures/stealth_file.py
(office creates those files as a local backup)
> add office formats to StealthFile white list

- data/yara/CAPE/BioPass.yar
- data/yara/CAPE/CryptBot.yar
- data/yara/CAPE/Downloaders.yar
- data/yara/CAPE/GoBrut.yar
- data/yara/CAPE/IAmTheKing.yar
- data/yara/CAPE/IAmTheKingKingOfHearts.yar
- data/yara/CAPE/IAmTheKingQueenOfClubs.yar
- data/yara/CAPE/IAmTheKingQueenOfHearts.yar
- data/yara/CAPE/JKeylogger.yar
- data/yara/binaries/indicator_suspicious.yar
- data/yara/binaries/indicator_tools.yar
- modules/signatures/network_cnc_encrypted.py
- modules/signatures/network_dns_suspicious.py
GoBrut > 171833
BioPass > 170915, 170959
JKeylogger > 170685
DLInjector* > 172107, 171918, 171733
CryptBot > 170995, 171869
> Add and update signatures

- modules/signatures/http_request.py
> add adobe, microsoft and digicert hosts to host_whitelist in http_req

- modules/signatures/antiemu_windefend.py
- modules/signatures/infostealer_cookies.py
> Fix listing matches

- data/yara/CAPE/HorusEyesRAT.yar
Just saw this one: 176886, 176887, 176894, 176895, 176896.
> Add detection for HorusEyesRAT

- modules/reporting/zexecreport.py
This makes it easy for feeding report.json into something arbitrary for additional processing.
> add a reporting module for assisting with processing via a arbitrary command

- modules/signatures/clamav.py
Fix clamav not work when analysis types are static, quarantine, etc.
> Fix clamav not work in some cases

- .github/workflows/python-package.yml
- pyproject.toml
Similar to changes made in the main repo
> Linting fix community

- modules/signatures/ransomware_message.py
This sig does not appear to work in original form. It has been modified to ignore completely dropped files which is no longer a possible detection point and merely check for a possible match in a file that is written as a likely ransomware match breaking (so it should get first match only for performance).
Extended also to .txt file to cover most though .htm and html files will need looked at also for possible ransom notes.
> Update ransomware message sig

- modules/signatures/bootkit.py
Added signature to detect when 512 bytes is written direct to drive. This specific value is the size of the MBR so suggests it being completely overwritten.
While other bootkits i have checked use other methods covered by other signatures it seems to be common in destructive wipers like NotPetya and the recent Whispergate (https://www.recordedfuture.com/whispergate-malware-corrupts-computers-ukraine/)
Whispergate
NotPetya
> Add signature for overwiting MBR with 512 bytes

- .github/update_mitre.py
- .github/workflows/update-mitre-files.yml
Workflow can be run manually to update the mitre files
> Add github workflow for updating of mitre files

- data/yara/CAPE/BackOffPOS.yar
Make the case match the module name for the config parser in CAPE.
> Update cape_type for BackOffPOS.

- .github/workflows/python-package.yml
Should fix the annoying issue where isort and black do not run together
> ci: update python-package workflow

- modules/signatures/office_suspicious_process.py
Added msdt.exe as office child process for Follina (CVE-2022-30190)
> Add MSDT for Follina to Office Suspicious Child

- modules/signatures/antiemu_windefend.py
- modules/signatures/bypass_uac.py
- modules/signatures/driver_filtermanager.py
- modules/signatures/modifies_dotnetclr_knobs.py
- modules/signatures/office_codepage.py
- modules/signatures/persistence_remotedesktop.py
- modules/signatures/territorial_disputes_sigs.py
- modules/signatures/uses_ms_protocol.py
For consistency https://github.com/kevoreilly/CAPEv2/blob/6de60f504e87fd8a59a182a3f3cdad8b604adddd/lib/cuckoo/common/abstracts.py#L725
> reference should be references

- modules/signatures/antisandbox_sunbelt_files.py
- modules/signatures/antisandbox_sunbelt_libs.py
- modules/signatures/antivm_generic_bios.py
- modules/signatures/antivm_generic_cpu.py
- modules/signatures/antivm_generic_services.py
- modules/signatures/antivm_hyperv_keys.py
- modules/signatures/antivm_vbox_devices.py
- modules/signatures/antivm_vbox_files.py
- modules/signatures/antivm_vbox_keys.py
- modules/signatures/antivm_vbox_libs.py
- modules/signatures/antivm_vbox_provname.py
- modules/signatures/antivm_vbox_window.py
- modules/signatures/antivm_vmware_devices.py
- modules/signatures/antivm_vmware_events.py
- modules/signatures/antivm_vmware_files.py
- modules/signatures/antivm_vmware_keys.py
- modules/signatures/antivm_vmware_libs.py
- modules/signatures/antivm_vmware_mutexes.py
- modules/signatures/antivm_vpc_files.py
- modules/signatures/antivm_vpc_keys.py
- modules/signatures/antivm_vpc_mutex.py
- modules/signatures/antivm_xen_keys.py
- modules/signatures/dropper.py
To match https://github.com/kevoreilly/CAPEv2/pull/911
> Mbc -> Mbcs

- modules/signatures/Log4shell.py
- modules/signatures/ek_neutrino.py
- modules/signatures/infostealer_raccoon.py
- modules/signatures/infostealer_vidar.py
- modules/signatures/locky_apis.py
- modules/signatures/ransomware_sodinokibi.py
- modules/signatures/rat_netwire.py
- modules/signatures/rat_orcus.py
- modules/signatures/rat_trochilus.py
- modules/signatures/removes_startmenu_defaults.py
- modules/signatures/trickbot_files.py
To be Pythonic and for consistency
> Renaming signatures to lower_snake_case

- data/yara/CAPE/BelialDropper.yar
- data/yara/CAPE/MatanbuchusLoader.yar
Thanks to @doomedraven for pointing out the difference earlier.
> Add belialdropper as a aleternative name for matanbuchus loader

- modules/signatures/overlay.py
in-line with https://github.com/kevoreilly/CAPEv2/pull/972
> feat: overlay signature

- analyzer/windows/modules/auxiliary/sysmon.py
- modules/processing/sysmon.py
This PR is based on this https://github.com/cuckoosandbox/cuckoo/pull/2518. Processing module PR is https://github.com/kevoreilly/CAPEv2/pull/994
> Updating the sysmon module

- modules/signatures/antiav_whitespace.py
- modules/signatures/antidebug_guardpages.py
- modules/signatures/antidebug_ntsetinformationthread.py
- modules/signatures/antisandbox_forehwnd.py
- modules/signatures/antivm_network_adapter.py
- modules/signatures/crypto_apis.py
- modules/signatures/deletes_executed.py
- modules/signatures/disables_security.py
- modules/signatures/dll_load_uncommon.py
- modules/signatures/modifies_zoneid_ads.py
- modules/signatures/network_cnc_http.py
- modules/signatures/network_dns_suspicious.py
- modules/signatures/network_p2p.py
- modules/signatures/network_payload_download.py
- modules/signatures/powershell_command.py
- modules/signatures/rat_senna.py
- modules/signatures/stealth_systemprocname.py
- modules/signatures/terminates_process.py
- modules/signatures/upatre_files.py
- modules/signatures/upatre_mutexes.py
- modules/signatures/wmi.py
REL https://github.com/kevoreilly/community/issues/283
This subset of missing Cuckoo signatures were the ones that I determined to have the highest successful hit rate based on the samples I've analyzed in the past.
I added a few signatures from PRs I made on the Cuckoo Community repo:
- https://github.com/cuckoosandbox/community/pull/480
- https://github.com/cuckoosandbox/community/pull/502
- https://github.com/cuckoosandbox/community/pull/503
- https://github.com/cuckoosandbox/community/pull/514
> Migrating key sigs from Cuckoo, adding a few useful ones

- modules/signatures/antisandbox_sleep.py
- modules/signatures/antivm_network_adapter.py
- modules/signatures/browser_security.py
- modules/signatures/crypto_apis.py
- modules/signatures/multiple_ua.py
- modules/signatures/network_icmp.py
- modules/signatures/office_suspicious.py
Most PRs from https://github.com/cuckoosandbox/community/pulls/cccs-kevin have been added via this PR. I ignored signatures that had not made the migration cut since they generated too many false positives.
> Updating signatures with safelisting, etc

- analyzer/windows/modules/auxiliary/curtain.py
- modules/processing/curtain.py
I suspect this module isn't maintained / supported by the CAPEv2 repo maintainers
REL https://github.com/kevoreilly/CAPEv2/pull/1026
NOTE: I added the following line to the `noise` tuple: 
`'"Get-WmiObject"\nParameterBinding(Get-WmiObject): name="ComputerName"; value="Localhost"\nParameterBinding(Get-WmiObject): name="Class"; value="win32_computersystem"\nCommandInvocation(Out-Default): "Out-Default"\nParameterBinding(Out-Default): name="Transcript"; value="True"\nParameterBinding(Out-Default): name="InputObject";'`
> Move curtain modules to the community repo

- modules/processing/sysmon.py
Not every exception has a message attribute
> Fixing sysmon error

- modules/signatures/network_bind.py
This is a pretty reliable signature
> Increasing score of network_bind sig

- modules/signatures/anomalous_deletefile.py
- modules/signatures/antisandbox_unhook.py
- modules/signatures/stack_pivot.py
These signatures were frequently found in a sample set of benign PDF files (~10K)
> Tweaking signatures that are frequently raised on benign PDF files

- modules/signatures/network_explorer.py
This signature, from what I can find, has a 100% true-positive rate.
> Increasing the severity of explorer_http

- analyzer/windows/modules/auxiliary/procmon.py
> Fix redundant execution in Procmon Auxiliary Module

- modules/signatures/office_macro_suspicious.py
Seems this was broken as was not providing results. This seems to be working now as expected but have a quick eye over it if you can to make sure correct format/conditions to expected format but is working now again
> Fix static olevba results

- modules/signatures/disables_crashdumps.py
Seen in HermeticWiper among others
> Create sig for disabling crash dumps

- modules/signatures/bootkit.py
Added signature for physical drive enumeration (accesses on multiple drives) and modified drive write to cover when more than one physical drive is accessed so they are shown. This is to cover wipers like CADDYWIPER
> Update physical drive write and add enumeration sig

- modules/signatures/ransomware_filemodifications.py
Added NtWriteFile check after NtCreateFile existing and reduced the hits back down to 50+. This will trigger now properly on actual overwriting of the file by a second API call. This was tested using CADDYWIPER and works.
> Combine NtWriteFile with overwrite existing (fix)

- modules/signatures/browser_addon.py
https://www.mandiant.com/resources/blog/lnk-between-browsers
> Add signature for loading Chromium browser from directory

- analyzer/linux/modules/auxiliary/sysmon.py
- analyzer/windows/modules/auxiliary/sysmon.py
- modules/processing/sysmon.py
Dependent on https://github.com/kevoreilly/CAPEv2/pull/1570
> Adding Sysmon auxiliary module for Linux

- utils/download_parsers.py
- utils/download_yara.py
Based on the conversation here: https://github.com/kevoreilly/CAPEv2/pull/1894
> Migrating download utilities for YARA and parsers to community

- utils/clone-machines.py
Closes https://cccs.atlassian.net/browse/AL-1891
> Updating clone-machines utility to support more options

- modules/signatures/all/antianalysis_tls.py
Add signature for threat local storage  PE section being present
https://attack.mitre.org/techniques/T1055/005/
> Add signature for .tls section

- modules/signatures/windows/bypass_uac.py
- modules/signatures/windows/credential_access.py
- modules/signatures/windows/credential_dumping.py
- modules/signatures/windows/deletes_consolehost_history.py
- modules/signatures/windows/exploit_spooler.py
- modules/signatures/windows/ipc_namedpipe.py
- modules/signatures/windows/lolbas.py
- modules/signatures/windows/misc.py
- modules/signatures/windows/ransomware_stopdjvu.py
- modules/signatures/windows/windows_utilities.py
Lately, I've been focusing on enhancing the sandbox environment to improve the detection of malicious and suspicious artifacts. I discovered a valuable [Elastic repository](https://github.com/elastic/protections-artifacts/tree/main/behavior/rules/windows) for identifying anomalies.
So far, I've added around 39 new artifacts and am continuing to work on expanding this collection.
> New Detection Artifacts

- modules/signatures/windows/disables_windefender.py
- modules/signatures/windows/lolbas.py
- modules/signatures/windows/misc.py
- modules/signatures/windows/persistence_autodial_dll.py
- modules/signatures/windows/remcos.py
I have added about new 19 detection rules related to Elastic and I have included also a new artifact to detect malicious activity using Restart Manager library See  [kevoreilly/capemon@83](https://github.com/kevoreilly/capemon/pull/83#issue-2615308486)
> Adding new artifacts

- modules/signatures/windows/system_location_discovery.py
Add some additional location discovery methods (for possible geofencing)
> Add additional location discovery methods

- modules/signatures/windows/windows_utilities.py
https://attack.mitre.org/techniques/T1218/013/
https://www.trendmicro.com/en_us/research/25/b/earth-preta-mixes-legitimate-and-malicious-components-to-sidestep-detection.html
> Add signature for Mavinject Lolbin

- modules/signatures/windows/bootkit.py
> Add signature for suspicious Device IO Control Codes
